# Generated by cpp11: do not edit by hand

cycles_cpp <- function(df, edge_list, start_edge_index, left) {
  .Call(`_neighbourhoods_cycles_cpp`, df, edge_list, start_edge_index, left)
}

cpp_reduce_paths <- function(edge_list) {
  .Call(`_neighbourhoods_cpp_reduce_paths`, edge_list)
}

cpp_expand_edges <- function(paths, edge_map_in) {
  .Call(`_neighbourhoods_cpp_expand_edges`, paths, edge_map_in)
}

cpp_preprocess <- function(df) {
  .Call(`_neighbourhoods_cpp_preprocess`, df)
}
