# Generated by cpp11: do not edit by hand

cycles_cpp <- function(df, edge_list, start_edge_index, left) {
  .Call(`_LTN_cycles_cpp`, df, edge_list, start_edge_index, left)
}

cpp_preprocess <- function(df) {
  .Call(`_LTN_cpp_preprocess`, df)
}
